#!/bin/sh

set -eu

PREFIX="$1"
OWN="$2"
shift 2

ARCHS="amd64 arm64"

. "$(dirname "$0")/common.in"

DOLLAR="\$\$"

get_arch_exclusions() {
	local df="$1"

	if [ -n "$df" ]; then
		grep '^# build:' "$df" 2>/dev/null \
			| grep -o '![a-z0-9_]*' \
			| sed 's/!//' \
			| tr '\n' ' ' \
			| sed 's/ *$//'
	fi
}

get_platform() {
	local excl=" $1 "
	local arch sep="" result=""

	for arch in $ARCHS; do
		case "$excl" in
		*" $arch "*) continue ;;
		esac
		result="${result}${sep}linux/${arch}"
		sep=","
	done
	echo "$result"
}

#
#
get_images() {
	cut -d' ' -f1 < "$1"
}

get_3rd_party() {
	local OWN="$1"
	local tag= dir= from= df=

	while read tag dir; do
		if [ ! -d "$dir" ]; then
			df=
		else
			df=$(get_dockerfile "$dir")
		fi

		if [ -n "$df" ]; then
			from="$(sed -n -e 's:^[ \t]*FROM[ \t]\+\([^ ]\+\).*$:\1:p' "$df")"
		else
			from="$dir"
		fi

		if [ -n "$from" ]; then
			if ! grep -q "^${from#$PREFIX} " "$OWN"; then
				echo "$from"
			fi
		fi
	done < "$OWN" | sort -uV
}

gen_image_files() {
	local dir="$1" df x
	shift

	df=$(get_dockerfile "$dir")

	(
	for x; do
		echo "$x"
	done

	# Extract files from COPY commands: skip --chown/--from/... option
	# flags and emit every source, dropping the trailing destination.
	awk -v dir="$dir" '
		$1 == "COPY" {
			n = 0
			for (i = 2; i <= NF; i++)
				if ($i !~ /^--/) tok[++n] = $i
			for (j = 1; j < n; j++) print dir "/" tok[j]
		}
	' "$df"

	# Include .in templates
	find "$dir" ! -type d -a -name '*.in' | sed -e 's|\.in$||'

	# Include Dockerfile itself
	echo "$dir/Dockerfile"

	) | sed -e "s|^$PWD/||" -e "s|^./||" | sort -uV
}

key() {
	local x=
	for x; do
		echo "$x" | tr ':' '-'
	done
}

prefix() {
	local x=
	for x; do
		echo "\$(PREFIX)$(key $x)"
	done
}

puller() {
	local x=
	for x; do
		echo "pull-$(key $x)"
	done
}

sentinel() {
	local x=
	for x; do
		x="$(echo "$x" | tr ':/' '-_')"
		echo "\$(B)/.image-$x"
	done
}

aliases() {
	local x=
	for x; do
		x="$(echo "$x" | tr ':/' '-_')"
		echo "\$(B)/.alias-$x"
	done
}

IMAGES=$(get_images "$OWN")
IMAGES_SHORT=$(echo "$IMAGES" | sed -e 's|:.*||' | sort -uV)
THIRD_PARTY=$(get_3rd_party "$OWN")

cat <<EOT
# generated by $0
#
$(list_key_f IMAGES prefix $IMAGES_SHORT)
$(list_key_f PULLERS puller $(sort_uV $IMAGES_SHORT $IMAGES $THIRD_PARTY))
EOT

# THIRD_PARTY
#
for tag in $THIRD_PARTY; do
	s1="$(sentinel "$tag")"
	k1="$(key "$tag")"
	d1="$(puller "$tag")"
	cat <<EOT

# $tag
#
.PHONY: $k1 $d1
$k1: $s1
$d1: $s1

$s1: \$(BUILD_SYS)
	\$(DOCKER) pull $tag
	touch \$@
EOT
done

# OWN
#
while read tag dir; do
	if [ ! -d "$dir" ]; then
		df=
		from=$dir
		dir=
	else
		df=$(get_dockerfile "$dir")
		from="$(sed -n -e 's:^[ \t]*FROM[ \t]\+\([^ ]\+\).*$:\1:p' "$df")"
	fi

	if grep -q "^${from#$PREFIX} " "$OWN"; then
		# Own base: its built image.
		s0=$(sentinel "${from#$PREFIX}")
		a0=$(aliases "${from#$PREFIX}")
	else
		# Third-party base: its pulled image.
		s0=$(sentinel "$from")
		a0=$s0
	fi

	k1=$(key $tag)
	d1=$(puller $tag)
	s1=$(sentinel $tag)
	a1=$(aliases $tag)

	if [ -z "$dir" ]; then
		files="$a0"
	else
		from=
		# Base sentinel is intentionally absent here: it is a gated
		# prerequisite below (publish mode only), not an unconditional
		# build input.
		files="$(gen_image_files "$dir" '$(BUILD_SYS)')"
	fi

	excl=$(get_arch_exclusions "$df")
	platform=$(get_platform "$excl")

	cat <<EOT

# $tag
#
.PHONY: \$(PREFIX)$k1
\$(PREFIX)$k1: $a1

.PHONY: $d1
$d1:
	\$(DOCKER) pull \$(PREFIX)$tag

$s1: PLATFORM = $platform
$(list_target $s1 $files)
EOT

if [ -d "$dir" ]; then
	# In the normal (publish) mode the base image — own build or
	# third-party pull — is made first so the FROM reference resolves
	# from local storage. A dev (BUILDER=) build drops this edge to stay
	# single-target and lets buildx pull whatever base is published.
	cat <<EOT
ifeq (\$(WANTS_TAGS),1)
$s1: $s0
endif
EOT

	# Optional run-hook.sh SHA256, hashed at build time and passed as a
	# build arg. Empty for images without a run-hook.
	RUN_HOOK_SHA256=
	if [ -f "$dir/run-hook.sh" ]; then
		RUN_HOOK_SHA256="${DOLLAR}(sha256sum \"$dir/run-hook.sh\" | cut -d' ' -f1)"
	fi

	# With tags: push the multi-arch manifest and seed the registry cache.
	# Without tags: build for the host and load it untagged, recording the
	# image ID in the sentinel. A dev build leaves no persistent tag, so
	# docker image prune reclaims it; reference it via $(cat sentinel).
	cat <<EOT
ifeq (\$(WANTS_TAGS),1)
	\$(DOCKER_BUILD) \$(DOCKER_BUILD_OPT) --platform \$(PLATFORM) --push \\
		${RUN_HOOK_SHA256:+--build-arg "RUN_HOOK_SHA256=$RUN_HOOK_SHA256" \\
		}--cache-to type=inline \\
		--cache-from type=registry,ref=\$(PREFIX)$tag \\
		-t \$(PREFIX)$tag \\
		$dir
	touch \$@
else
	\$(DOCKER_BUILD) \$(DOCKER_BUILD_OPT) --load \\
		${RUN_HOOK_SHA256:+--build-arg "RUN_HOOK_SHA256=$RUN_HOOK_SHA256" \\
		}--iidfile \$@~ \\
		$dir
	mv \$@~ \$@
endif

$a1: $s1
ifeq (\$(WANTS_TAGS),1)
	@\$(SCRIPTS)/get_aliases.sh \$(PREFIX)$tag | while read x; do \\
		\$(DOCKER_TAG) -t ${DOLLAR}x \$(PREFIX)$tag; \\
	done
endif
	touch \$@
EOT
else
	# Alias-only tag: retag the registry manifest. Local builds are
	# untagged and single-target, so there is no tag to copy and the
	# alias resolves to a no-op.
	cat <<EOT
ifeq (\$(WANTS_TAGS),1)
	\$(DOCKER_TAG) -t \$(PREFIX)$tag \$(PREFIX)$from
endif
	touch \$@

$a1: $s1
	touch \$@
EOT
fi

done < "$OWN"

# shortcuts
#
for x in $IMAGES_SHORT; do

	k1=$(prefix $x)
	d1=$(puller $x)
	s1=$(sentinel $x)

	sub="$(grep "$x:" "$OWN" | cut -d' ' -f1)"

	cat <<EOT

# $x
#
.PHONY: $k1
$k1: $s1

.PHONY: $d1
$(list_target_f $d1 puller $sub)

$(list_target_f $s1 aliases $sub)
	touch \$@
EOT
done
